import { ROPAActivity } from './types';

export const initialActivities: ROPAActivity[] = [
  {
    id: 'ropa-001',
    name: 'Client Onboarding',
    purpose: 'Collecting name, email, and business details to deliver services',
    lawfulBasis: 'Contract',
    dataSubjects: 'Clients',
    personalData: 'Name, email address, business name, business type',
    recipients: 'Google Workspace',
    internationalTransfers: false,
    transferDetails: '',
    retentionPeriod: 'Duration of engagement plus 6 years',
    securityMeasures: 'Google Workspace access controls, limited to data controller only',
    dateAdded: '2026-04-19',
    lastReviewed: '2026-04-19',
  },
  {
    id: 'ropa-002',
    name: 'Service Delivery',
    purpose: 'Processing client data to complete gap analysis, policies, and compliance work',
    lawfulBasis: 'Contract',
    dataSubjects: 'Clients',
    personalData: 'Business data, existing policies, tool lists, processing activities',
    recipients: 'Google Workspace, Claude (Anthropic)',
    internationalTransfers: true,
    transferDetails: 'Anthropic (US). Covered by SCCs.',
    retentionPeriod: '6 years post-engagement',
    securityMeasures: 'Google Drive access controls, password protected',
    dateAdded: '2026-04-19',
    lastReviewed: '2026-04-19',
  },
  {
    id: 'ropa-003',
    name: 'Email Marketing',
    purpose: 'Sending newsletters and updates to subscribers who have opted in',
    lawfulBasis: 'Consent',
    dataSubjects: 'Subscribers',
    personalData: 'Name, email address',
    recipients: 'Email marketing platform',
    internationalTransfers: false,
    transferDetails: 'To be confirmed based on platform used',
    retentionPeriod: 'Until unsubscribe or consent withdrawn',
    securityMeasures: 'Platform-level security, unsubscribe available in every email',
    dateAdded: '2026-04-19',
    lastReviewed: '2025-03-01',
  },
  {
    id: 'ropa-004',
    name: 'Discovery Call Bookings',
    purpose: 'Collecting name and email via Google Calendar booking link to schedule calls',
    lawfulBasis: 'Legitimate interests',
    dataSubjects: 'Prospective clients',
    personalData: 'Name, email address, any notes submitted at booking',
    recipients: 'Google Calendar',
    internationalTransfers: true,
    transferDetails: 'Google LLC (US). Covered by SCCs.',
    retentionPeriod: '12 months',
    securityMeasures: 'Google Workspace access controls',
    dateAdded: '2026-04-19',
    lastReviewed: '2026-01-15',
  },
  {
    id: 'ropa-005',
    name: 'Digital Product Sales',
    purpose: 'Processing purchase data for template and digital product transactions via Beacons',
    lawfulBasis: 'Contract',
    dataSubjects: 'Customers',
    personalData: 'Name, email address, payment reference',
    recipients: 'Beacons, payment processor',
    internationalTransfers: true,
    transferDetails: 'Beacons (US). Covered by SCCs.',
    retentionPeriod: '6 years (financial records)',
    securityMeasures: 'Platform-level security via Beacons',
    dateAdded: '2026-04-19',
    lastReviewed: '2026-01-15',
  },
  {
    id: 'ropa-006',
    name: 'Content Analytics',
    purpose: 'Reviewing TikTok and Instagram analytics to inform content strategy',
    lawfulBasis: 'Legitimate interests',
    dataSubjects: 'Content viewers (aggregated only)',
    personalData: 'Aggregated analytics data only — no individual personal data stored directly',
    recipients: 'TikTok, Instagram (Meta)',
    internationalTransfers: true,
    transferDetails: 'TikTok (US/Singapore), Meta (US). Platform-level compliance.',
    retentionPeriod: 'Not stored — reviewed in-platform only',
    securityMeasures: 'Platform-level security',
    dateAdded: '2026-04-19',
    lastReviewed: '2025-02-15',
  },
  {
    id: 'ropa-007',
    name: 'Supplier and Tool Management',
    purpose: 'Storing details of third-party tools and suppliers used to operate the business',
    lawfulBasis: 'Legitimate interests',
    dataSubjects: 'Suppliers and tool providers (minimal personal data — contact names only)',
    personalData: 'Contact name, email, tool name, subscription details',
    recipients: 'Internal only',
    internationalTransfers: false,
    transferDetails: '',
    retentionPeriod: 'Duration of use plus 1 year',
    securityMeasures: 'Google Workspace access controls',
    dateAdded: '2026-04-19',
    lastReviewed: '2026-03-01',
  },
];
